exp:
  exp_name: ['barbell']
  wandb: [True]
  num_seeds: [4]
  device: [0]
  seed: [93428]
data:
  dataset: ['barbell']
  samples: [100]
  task_type: ['mse_regression']
  eval_metric: ['mse']
  minimize: [True]
  num_nodes: [10]
model:
  model_name: ['rwnn']
  input_dim: [1]
  hidden_dim: [128]
  out_dim: [1]
  num_layers: [1]
  min_degree: [True]
  no_backtrack: [True]
  walk_len: [200]
  train_n_walks: [8]
  eval_n_walks: [1]
  test_n_walks: [32]
optim:
  lr: [0.0001]
  lr_scheduler: ['None']
  early_stop: [False]
  epochs: [500]
  batch_size: [1]